# ==============================================
# BourseChain - ConfigMap
# Sprint 6 - Orchestration
# ==============================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: boursechain-config
  namespace: boursechain
  labels:
    app.kubernetes.io/name: boursechain
data:
  # Django
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"

  # Database
  DB_NAME: "boursechain"
  DB_USER: "postgres"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"

  # Redis
  REDIS_URL: "redis://redis-service:6379/1"
  CHANNEL_REDIS_URL: "redis://redis-service:6379/3"

  # Celery
  CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq-service:5672//"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/2"

  # Blockchain
  BLOCKCHAIN_ENABLED: "True"
  BLOCKCHAIN_RPC_URL: "http://hardhat-service:8545"

  # CORS
  CORS_ALLOWED_ORIGINS: "http://localhost,http://boursechain.local"

  # SIWE
  SIWE_DOMAIN: "boursechain.local"
  SIWE_URI: "http://boursechain.local"
